"""
Script 01: Process ONS Retail Sales Index (RSI) Data Offline
Loads and parses the manually downloaded 'ons_retail_sales.xlsx' file safely using absolute paths.
"""

import pandas as pd
import os
import sys

# Connect cleanly to config variables from the root folder
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import RAW_DATA_PATH, PROCESSED_DATA_PATH


def build_clean_retail_dataframe():
    # Use the absolute path generated by config.py
    filepath = os.path.join(RAW_DATA_PATH, "ons_retail_sales.xlsx")

    if not os.path.exists(filepath):
        print(f"ERROR: Local retail file not found at {filepath}")
        print(
            "Please ensure your downloaded file is named 'ons_retail_sales.xlsx' and sits in the main data/raw/ folder!")
        return None

    print(f"Opening local ONS Retail Sales workbook: {filepath}")
    xl = pd.ExcelFile(filepath)

    # Target the main monthly volume tracking data sheet (Usually Sheet 2)
    target_sheet = xl.sheet_names[1]
    for sheet in xl.sheet_names:
        if 'kp' in sheet.lower() or 'volume' in sheet.lower() or 'table 1' in sheet.lower():
            target_sheet = sheet
            break

    print(f"Parsing sheet matrix data from: '{target_sheet}'")
    df_raw = pd.read_excel(filepath, sheet_name=target_sheet, header=None)

    # Find the data row boundaries starting near standard timelines (e.g., 2015 baseline entries)
    header_idx = 0
    for idx, row in df_raw.iterrows():
        row_str = " ".join([str(v).lower() for v in row.values])
        if '2015' in row_str or 'jan' in row_str or 'year' in row_str:
            header_idx = idx
            break

    print(f"Data anchor row detected at line index: {header_idx}")
    df = pd.read_excel(filepath, sheet_name=target_sheet, header=header_idx)
    df.columns = [str(c).strip().lower() for c in df.columns]

    # Establish base tracking date column index reference
    date_col = df.columns[0]
    df = df.rename(columns={date_col: 'date_string'})

    # Clean the rows: filter for text entries containing 4-digit years (e.g., '2015 JAN')
    df['date_clean'] = df['date_string'].astype(str).str.strip().str.upper()
    df = df[df['date_clean'].str.contains(r'^\d{4}\s+[A-Z]', regex=True, na=False)].copy()

    # Convert text strings cleanly into timestamp date representations
    df['parsed_date'] = pd.to_datetime(df['date_clean'].str.slice(0, 8), format='%Y %b', errors='coerce')
    df = df.dropna(subset=['parsed_date'])

    # Extract structural date integer elements
    df['year'] = df['parsed_date'].dt.year
    df['month'] = df['parsed_date'].dt.month

    # Filter strictly for project scope boundaries
    df = df[df['year'] >= 2015]
    df = df.rename(columns={'parsed_date': 'date'})

    # Dynamically select and rename structural retail market columns positionally
    rename_rules = {}
    data_columns = [c for c in df.columns if c not in ['date_string', 'date_clean', 'date', 'year', 'month']]

    if len(data_columns) >= 1: rename_rules[data_columns[0]] = 'retail_total_volume'
    if len(data_columns) >= 2: rename_rules[data_columns[1]] = 'retail_food_volume'
    if len(data_columns) >= 3: rename_rules[data_columns[2]] = 'retail_non_food_volume'
    if len(data_columns) >= 5: rename_rules[data_columns[4]] = 'retail_online_volume'

    df = df.rename(columns=rename_rules)

    # Standardize numerical values cleanly
    target_cols = ['retail_total_volume', 'retail_food_volume', 'retail_non_food_volume', 'retail_online_volume']
    for col in target_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
        else:
            df[col] = 100.0

    final_cols = ['date', 'year', 'month'] + target_cols
    df_final = df[final_cols].sort_values('date').reset_index(drop=True)

    # Save the output file safely inside the true processed folder path
    output_path = os.path.join(PROCESSED_DATA_PATH, "ons_retail_clean.csv")
    df_final.to_csv(output_path, index=False)

    print(f"\nSUCCESS: Saved clean local ONS Retail Sales schema ({len(df_final)} rows) to: {output_path}")
    return df_final


if __name__ == "__main__":
    print("=" * 60)
    print("Local ONS Retail Sales Processing Engine")
    print("=" * 60)
    df = build_clean_retail_dataframe()
    if df is not None and not df.empty:
        print("\n--- Processed Retail Sample Preview ---")
        print(df.head(12))